### ISSUE TITLE
Scoped styles do not work correct with this plugin

### ISSUE THREAD

**Issue by edwinofsakh** [trapcodeio/vite-plugin-ejs#5]
If scoped styles are used with this plugin Vite regenerates data-v-xxxxx id instead of using scoped from URL.

I use `vite@3.2.2` and `vite-plugin-ejs@1.5.0`

**Comment by trapcodeio** [comment]
Greetings

Do you have a repo or stackblitz link to reproduce this error?

**Comment by trapcodeio** [comment]
Kindly re-open issue when you are available to work it out. Thanks

**Comment by dynomind-dev** [comment]
It works good in version 1.6.4.
