### ISSUE TITLE
Plugin dont work if index.html is not in the root directory

### ISSUE THREAD

**Issue by realtoptuk** [trapcodeio/vite-plugin-ejs#8]
Thank you for your plugin.

I've noticed that if index.html is placed in some subdirectory, yours plugin wont work and there is an error:
**Unable to parse HTML; parse5 error code invalid-first-character-of-tag-name**

Reproduction link: https://stackblitz.com/edit/vite-plugin-ejs-25tecb?file=vite.config.js

Maybe im doing something wrong? If so, I'll appreciate your advice how to fix it and add this in docs, maybe.

**Comment by trapcodeio** [comment]
Greetings

You need to move the partials folder to your `public` folder which is now your new **root**.
But if you don't want that, you can set a custom partials folder like the code below

```js
export default defineConfig({
  root: 'public',
  plugins: [
    ViteEjsPlugin(
      () => {
        return {
          title: 'My vue project!',
        };
      },
      {
        ejs: {
          views: [__dirname],
        },
      }
    ),
  ],
});
```

**Comment by realtoptuk** [comment]
Thank you for your response. It is very ease to think about.

**Comment by nosovk** [comment]
Working [stackblitz](https://stackblitz.com/edit/vite-plugin-ejs-zukfi4?file=vite.config.js)
